-- +goose envsub on
-- +goose Up
CREATE DATABASE IF NOT EXISTS `${CORE_DB_NAME}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `${CITY_DB_NAME}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `${INDUSTRY_DB_NAME}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `${SKI_DB_NAME}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- +goose Down
DROP DATABASE IF EXISTS `${CORE_DB_NAME}`;
DROP DATABASE IF EXISTS `${CITY_DB_NAME}`;
DROP DATABASE IF EXISTS `${INDUSTRY_DB_NAME}`;
DROP DATABASE IF EXISTS `${SKI_DB_NAME}`;
