-- +goose envsub on
-- +goose Up
GRANT ALL PRIVILEGES ON `${CORE_DB_NAME}`.* TO `${MYSQL_USER}`@`%`;
GRANT ALL PRIVILEGES ON `${CITY_DB_NAME}`.* TO `${MYSQL_USER}`@`%`;
GRANT ALL PRIVILEGES ON `${INDUSTRY_DB_NAME}`.* TO `${MYSQL_USER}`@`%`;
GRANT ALL PRIVILEGES ON `${SKI_DB_NAME}`.* TO `${MYSQL_USER}`@`%`;

-- +goose Down
REVOKE ALL PRIVILEGES ON `${CORE_DB_NAME}`.* FROM `${MYSQL_USER}`@`%`;
REVOKE ALL PRIVILEGES ON `${CITY_DB_NAME}`.* FROM `${MYSQL_USER}`@`%`;
REVOKE ALL PRIVILEGES ON `${INDUSTRY_DB_NAME}`.* FROM `${MYSQL_USER}`@`%`;
REVOKE ALL PRIVILEGES ON `${SKI_DB_NAME}`.* FROM `${MYSQL_USER}`@`%`;
